#!/bin/bash
set -ex

if [ -e /var/lib/mysql/image-slow.log ]; then
    sudo mv /var/lib/mysql/image-slow.log /var/lib/mysql/image-slow.log.$(date "+%Y%m%d_%H%M%S")
fi

if [ -e /var/log/nginx/access.log ]; then
    sudo mv /var/log/nginx/access.log /var/log/nginx/access.log.$(date "+%Y%m%d_%H%M%S")
fi
/home/isucon/private_isu/webapp/deploy/restart
